#!/usr/bin/ruby

require_relative 'rerun'
require_relative 'runscripts'
require_relative 'functionality'
require_relative 'performance'
include RunScripts

#------------------------------------------------------------------------------
# Rerun
#------------------------------------------------------------------------------
# rerun

#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
# single_short
# baseline_short
# secure_short
# donor_short
# monotonic_short
# inv_prio_short
# tp_config_test
maxmem_test

#------------------------------------------------------------------------------
# Performance
#----------------------------------------------------------------------------
# baseline
# single_core
# synthetic
# secure_spec
