#!/usr/bin/ruby

require_relative 'rerun'
require_relative 'runscripts'
require_relative 'functionality'
require_relative 'performance'
include RunScripts

#------------------------------------------------------------------------------
# Rerun
#------------------------------------------------------------------------------
# rerun

#------------------------------------------------------------------------------
# Functionality
#------------------------------------------------------------------------------
# single_short
# baseline_short
# secure_short
# all_secure_test
diamond_test

#------------------------------------------------------------------------------
# Performance
#----------------------------------------------------------------------------
#baseline
#single_core
#secure_spec
#synthetic
